# version: '3.8'

# services:
#   api:
#     container_name: web-api
#     build: 
#       context: .
#     ports:
#       - 1323:1323
#     depends_on:
#       - postgres
#     env_file:
#       - .env

#   postgres:
#     container_name: postgres-db
#     image: postgres:latest
#     ports:
#       - 5432:5432
#     restart: always
#     environment:
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: mypassword
#       POSTGRES_DB: testdb
   